version: '3.8'

services:
  api:
    build:
      context: ./api
    container_name: api_container
    ports:
      - "4000:4000"
    # depends_on:
    #   - database
    volumes:
      - ./api:/api
      - /api/node_modules #anonymous volume-map our container's node_modules
    networks:
      - mynetwork

  ui: 
    build: 
      context: ./ui
    container_name: ui_container
    ports:
      - "3002:3002"
    depends_on:
      - api
    volumes:
      - ./ui:/ui
      - /ui/node_modules
    networks:
      - mynetwork

  dashboard:
    build:
      context: ./Dashboard
    container_name: dashboard_container
    ports:
      - "3003:3003"
    depends_on:
      - api
    volumes:
      - ./Dashboard:/dashboard
      - /dashboard/node_modules
    networks:
      - mynetwork

  database:
    image: postgres:latest
    container_name: db_container
    environment:
      POSTGRES_USER: em_db_odk4_user
      POSTGRES_PASSWORD: iBIDxKl0BM4LU1bXhcSaqDq61FRk7GLr
      POSTGRES_DB: em_db_odk4 
    ports:
      - "5432:5432"
networks:
  mynetwork:
    driver: bridge